### Create booking request (non-recurring and officeId) for one day
POST {{host}}/booking/any
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "officeId": "{{activeOfficeId}}",
  "workplaceId": null,
  "userId": "{{userId}}",
  "startDate": "2022-04-13",
  "endDate": null,
  "isRecurring": false,
  "datesList": null
}

### Create booking request (non-recurring and officeId) for continous dates
POST {{host}}/booking/any
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "officeId": "{{activeOfficeId}}",
  "workplaceId": null,
  "userId": "{{userId}}",
  "startDate": "2022-04-13",
  "endDate": "2022-04-15",
  "isRecurring": false,
  "datesList": null
}


### Create booking request (recurring and officeId) with dates list
POST {{host}}/booking/any
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "officeId": "{{activeOfficeId}}",
  "workplaceId": null,
  "userId": "{{userId}}",
  "startDate": null,
  "endDate": null,
  "isRecurring": true,
  "datesList": [
    "2022-02-10",
    "2022-02-11"
  ]
}

### Create booking request (non-recurring and workplaceId) for one day
POST {{host}}/booking
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "officeId": null,
  "workplaceId": "{{activeWorkplaceId}}",
  "userId": "{{userId}}",
  "startDate": "2022-04-13",
  "endDate": null,
  "isRecurring": false,
  "datesList": null
}

### Create booking request (non-recurring and workplaceId) for continous dates
POST {{host}}/booking
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "officeId": null,
  "workplaceId": "{{activeWorkplaceId}}",
  "userId": "{{userId}}",
  "startDate": "2022-04-13",
  "endDate": "2022-04-15",
  "isRecurring": false,
  "datesList": null
}


### Create booking request (recurring and workplaceId) with dates list
POST {{host}}/booking
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "officeId": null,
  "workplaceId": "{{activeWorkplaceId}}",
  "userId": "{{userId}}",
  "startDate": null,
  "endDate": null,
  "isRecurring": true,
  "datesList": [
    "2022-05-10",
    "2022-05-11"
  ]
}

### Save bookings by IDs
POST {{host}}/booking/save
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "list": [
    "ff8081817fb7ed0c017fb7f969ae0002",
    "ff8081817fb7ed0c017fb7f969ae0003",
    "ff8081817fb7ed0c017fb7efa1b60000"
  ]
}

### Cancel booking by id
POST {{host}}/booking/cancel?id=ff8081817fb7ed0c017fb7f969ae0003
Content-Type: application/json
Authorization: Bearer {{token}}

### Cancel booking by user id
POST {{host}}/booking/cancel?userId=ff8081817fb6f11b017fb6f179da0001&all=true
Content-Type: application/json
Authorization: Bearer {{token}}

### Cancel all bookings (DANGER!)
POST {{host}}/booking/cancel?all=true
Content-Type: application/json
Authorization: Bearer {{token}}

### Get booking by id
GET {{host}}/booking/ff8081817fb7ed0c017fb7f969ae0002
Content-Type: application/json
Authorization: Bearer {{token}}

### Get booking by user id
GET {{host}}/booking/userId/{{userId}}
Content-Type: application/json
Authorization: Bearer {{token}}

### Edit booking (non-recurring and workplaceId)
PUT {{host}}/booking/ff8081817fb6f11b017fb6f2287f0019
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "officeId": null,
  "workplaceId": "{{activeWorkplaceId}}",
  "userId": "{{userId}}",
  "startDate": "2022-04-27",
  "endDate": "2022-04-27",
  "isRecurring": false,
  "datesList": null
}

### Delete booking by id
DELETE {{host}}/booking/ff8081817fb7ed0c017fb7f969ae0002
Content-Type: application/json
Authorization: Bearer {{token}}

