###
<!--
Any Booking recurring CREATE request with dates list
-->
###
POST http://localhost:8123/api/booking/any
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5NTI2MzMzMzgiLCJpYXQiOjE2NDc1NDgyMzcsImV4cCI6MTY0NzYzNDYzN30.dz_PedDP-4oXD8pYXi-T3PAr2B8Ay16j1vBAQ6MfaxAzEHz6v--43dZbQpdusxByT61Mmq9ZlHdkpE4V1I1OTw

{
  "userId": "17f2277680f0000",
  "officeId": "test5",
  "startDate": null,
  "endDate": null,
  "isRecurring": true,
  "frequency": 1,
  "daysOfWeek": null,
  "datesList": [
    "2022-02-10",
    "2022-02-11"
  ]

}


###
<!--
Any Booking non-recurring one-day CREATE request with Office ID
-->
###
POST http://localhost:7123/api/booking/any
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5NTI2MzMzMzgiLCJpYXQiOjE2NDcxNzA2NTEsImV4cCI6MTY0NzI1NzA1MX0.nQNi_d5ZtQzKMh6LM7CAtpUJTHfYPpJnMji6431jdGTzFqnu4r3L1TsxtvGUPF-a6mTL5LAkUzOKYVgxWBvFCw

{
  "userId": "17f2277680f0000                 ",
  "officeId": "test5",
  "startDate": "2022-03-13",
  "endDate": null,
  "isRecurring": false,
  "frequency": 1,
  "daysOfWeek": null,
  "datesList": null
}


###
<!--
Any Booking non-recurring continuous CREATE request with Office ID
-->
###
POST http://localhost:7123/api/booking/any
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5NTI2MzMzMzgiLCJpYXQiOjE2NDcxNzA2NTEsImV4cCI6MTY0NzI1NzA1MX0.nQNi_d5ZtQzKMh6LM7CAtpUJTHfYPpJnMji6431jdGTzFqnu4r3L1TsxtvGUPF-a6mTL5LAkUzOKYVgxWBvFCw

{
  "userId": "17f2277680f0000                 ",
  "officeId": "test5",
  "startDate": "2022-03-13",
  "endDate": "2022-03-15",
  "isRecurring": false,
  "frequency": 1,
  "daysOfWeek": null,
  "datesList": null
}

###
<!--
Booking non-recurring continuous CREATE request with Workplace ID
-->
###
POST http://localhost:7123/api/booking/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5NTI2MzMzMzgiLCJpYXQiOjE2NDcxNzA2NTEsImV4cCI6MTY0NzI1NzA1MX0.nQNi_d5ZtQzKMh6LM7CAtpUJTHfYPpJnMji6431jdGTzFqnu4r3L1TsxtvGUPF-a6mTL5LAkUzOKYVgxWBvFCw

{
  "workplaceId": "testWRK                         ",
  "userId": "17f2277680f0000                 ",
  "startDate": "2022-02-24",
  "endDate": "2022-02-26",
  "isRecurring": false,
  "frequency": 1,
  "daysOfWeek": null,
  "datesList": null
}


###
<!--
Booking non-recurring one-day CREATE request with Workplace ID
-->
###
POST http://localhost:7123/api/booking/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5NTI2MzMzMzgiLCJpYXQiOjE2NDcxNzA2NTEsImV4cCI6MTY0NzI1NzA1MX0.nQNi_d5ZtQzKMh6LM7CAtpUJTHfYPpJnMji6431jdGTzFqnu4r3L1TsxtvGUPF-a6mTL5LAkUzOKYVgxWBvFCw

{
  "workplaceId": "testWRK                         ",
  "userId": "17f2277680f0000                 ",
  "startDate": "2022-01-24",
  "endDate": null,
  "isRecurring": false,
  "frequency": 1,
  "daysOfWeek": null,
  "datesList": null
}


###
<!--
Booking recurring CREATE request with Workplace ID and dates list
-->
###
POST http://localhost:7123/api/booking/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5NTI2MzMzMzgiLCJpYXQiOjE2NDcxNzA2NTEsImV4cCI6MTY0NzI1NzA1MX0.nQNi_d5ZtQzKMh6LM7CAtpUJTHfYPpJnMji6431jdGTzFqnu4r3L1TsxtvGUPF-a6mTL5LAkUzOKYVgxWBvFCw

{
  "workplaceId": "testWRK                         ",
  "userId": "17f2277680f0000                 ",
  "startDate": null,
  "endDate": null,
  "isRecurring": true,
  "frequency": 1,
  "daysOfWeek": null,
  "datesList": [
    "2022-01-11",
    "2022-01-15",
    "2022-01-17"
  ]
}

###
<!--
Booking report get by office ID
-->
###
GET http://localhost:7123/api/report/officeId/ff8081817fb07b88017fb07b99d50003
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5NTI2MzMzMzgiLCJpYXQiOjE2NDc5NTA2MTcsImV4cCI6MTY0ODAzNzAxN30.JsJYNgHlZC-Nu6J8EqfTa4OqsUkQlgK4sDd6SyLuyAePNSjwpRo__Q14BzXGdTSfymWQHaxC_uDZMnZnoaQ5RQ
###
<!--
Booking report get by office ID
-->
###
GET http://localhost:7123/api/report/excel/officeId/test5?startDate="2022-01-01"
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5NTI2MzMzMzgiLCJpYXQiOjE2NDczNjQyMjQsImV4cCI6MTY0NzQ1MDYyNH0.QflRoEiytBt7A7gmge224cN42dqP1FfJFs8A7xscu7E0kqFRiD3BlvP5ZP0M7kFcKKbHhA6uBjh3I8IWwGJl9Q

###
GET http://localhost:7123/api/report/all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5NTI2MzMzMzgiLCJpYXQiOjE2NDc5NTA2MTcsImV4cCI6MTY0ODAzNzAxN30.JsJYNgHlZC-Nu6J8EqfTa4OqsUkQlgK4sDd6SyLuyAePNSjwpRo__Q14BzXGdTSfymWQHaxC_uDZMnZnoaQ5RQ
