### Login request
POST {{host}}/login
Content-type: application/json

{
  "username": "952633338",
  "password": "password"
}

### Get current user
GET {{host}}/login/current
Content-Type: application/json
Authorization: Bearer {{token}}



