### Adding a new map
POST {{host}}/map
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "office_id": "ff8081817fb5b2dd017fb6515ea90001",
  "floor": 2,
  "kitchen": true,
  "conf_rooms": true
}


### Getting map by id
GET {{host}}/map/ff8081817fb6571e017fb657f2f10000
Authorization: Bearer {{token}}

### Deleting map
DELETE {{host}}/map/ff8081817fb5b2dd017fb653fa070002
Authorization: Bearer {{token}}

### Updating map
PUT {{host}}/map/ff8081817fb6571e017fb657f2f10000
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "office_id": "ff8081817fb5b2dd017fb6515ea90001",
  "floor": 4,
  "kitchen": false,
  "conf_rooms": false
}