### Adding a new map
POST {{host}}/map
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "office_id": "{{activeOfficeId}}",
  "floor": 4,
  "kitchen": true,
  "conf_rooms": true
}


### Getting map by id
GET {{host}}/map/{{activeMapId}}
Authorization: Bearer {{token}}

### Deleting map
DELETE {{host}}/map/ff8081817fb5b2dd017fb653fa070002
Authorization: Bearer {{token}}

### Updating map
PUT {{host}}/map/{{activeMapId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "office_id": "{{activeOfficeId}}",
  "floor": 4,
  "kitchen": false,
  "conf_rooms": false
}