### Getting all offices list
GET {{host}}/office
Authorization: Bearer {{token}}


### Getting office by city name
GET {{host}}/office/city/Tashkent
Authorization: Bearer {{token}}


### Adding office
POST {{host}}/office
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Office 5",
  "country": "Uzbekistan",
  "city": "Tashkent",
  "address": "Chilonzor-9",
  "is_parking_available": false
}


### Get office details (with map IDs) by office id
GET {{host}}/office/2c9f89f97fbaa511017fbacf8bee0000
Authorization: Bearer {{token}}



### Updating already existing office
PUT {{host}}/office/2c9f89f97fbaa511017fbacf8bee0000
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Office 33",
  "country": "Belarus",
  "city": "Minsk",
  "address": "Tashkent Street",
  "is_parking_available": false
}


### Deleting the office by office id
DELETE {{host}}/office/2c9f89f97fbaa511017fbacf8bee0000
Authorization: Bearer {{token}}




### Getting all the cities regarless of country
GET {{host}}/office/cityList
Authorization: Bearer {{token}}



### Getting all the cities in the country by country name
GET {{host}}/office/cityList/Uzbekistan
Authorization: Bearer {{token}}



### Getting countries list
GET {{host}}/office/countryList
Authorization: Bearer {{token}}



### Getting mapList by officeId
GET {{host}}/office/mapList/{{activeOfficeId}}
Authorization: Bearer {{token}}


### Checking whether the specific office has parking slot free
GET {{host}}/office/parking/ff8081817fb5357d017fb53588bc0003
Authorization: Bearer {{token}}
