

###
<!--
Any Booking recurring CREATE request with dates list
-->
###
POST {{host}}/booking/any
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userId": "17f2277680f0000",
  "officeId": "test5",
  "startDate": null,
  "endDate": null,
  "isRecurring": true,
  "frequency": 1,
  "daysOfWeek": null,
  "datesList": [
    "2022-02-10",
    "2022-02-11"
  ]

}


###
<!--
Any Booking non-recurring one-day CREATE request with Office ID
-->
###
POST {{host}}/booking/any
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userId": "17f2277680f0000                 ",
  "officeId": "test5",
  "startDate": "2022-03-13",
  "endDate": null,
  "isRecurring": false,
  "frequency": 1,
  "daysOfWeek": null,
  "datesList": null
}


###
<!--
Any Booking non-recurring continuous CREATE request with Office ID
-->
###
POST {{host}}/booking/any
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userId": "17f2277680f0000                 ",
  "officeId": "test5",
  "startDate": "2022-03-13",
  "endDate": "2022-03-15",
  "isRecurring": false,
  "frequency": 1,
  "daysOfWeek": null,
  "datesList": null
}

###
<!--
Booking non-recurring continuous CREATE request with Workplace ID
-->
###
POST {{host}}/booking/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "workplaceId": "testWRK                         ",
  "userId": "17f2277680f0000                 ",
  "startDate": "2022-02-24",
  "endDate": "2022-02-26",
  "isRecurring": false,
  "frequency": 1,
  "daysOfWeek": null,
  "datesList": null
}


###
<!--
Booking non-recurring one-day CREATE request with Workplace ID
-->
###
POST {{host}}/booking/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "workplaceId": "testWRK                         ",
  "userId": "17f2277680f0000                 ",
  "startDate": "2022-01-24",
  "endDate": null,
  "isRecurring": false,
  "frequency": 1,
  "daysOfWeek": null,
  "datesList": null
}


###
<!--
Booking recurring CREATE request with Workplace ID and dates list
-->
###
POST {{host}}/booking/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "workplaceId": "testWRK                         ",
  "userId": "17f2277680f0000                 ",
  "startDate": null,
  "endDate": null,
  "isRecurring": true,
  "frequency": 1,
  "daysOfWeek": null,
  "datesList": [
    "2022-01-11",
    "2022-01-15",
    "2022-01-17"
  ]
}

###
<!--
Save/confirm booking
-->

###
POST {{host}}/booking/save
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5NTI2MzMzMzgiLCJpYXQiOjE2NDc0NDE0MDQsImV4cCI6MTY0NzUyNzgwNH0.XQ69jvuD6bYh6JjXM7XtV5iGbLAGtLH0Qxs5QiozeHrlGCIx8nfqR0ATXHEriruaC8j9V1ZxlvXTTWx_PgZ6yA

{
  "list": [
    "ff8081817f8359e2017f835d5c980000",
    "ff8081817f831114017f8312d1a30001"
  ]
}

###
<!--
Booking report get by office ID
-->

###
GET {{host}}/report/excel/officeId/ff8081817fb24925017fb2493a270003
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5NTI2MzMzMzgiLCJpYXQiOjE2NDc5NjM4MjgsImV4cCI6MTY0ODA1MDIyOH0.y31DIdjvlAK7Fr-50Ub7kqErmFQeHdGbioRFCWv_DE6bLC6d6AYXgv2_8tBwn0_I_VtuX1cLoDUJr8VFCvpDMg

###
<!--
Booking report get by office ID
-->

###
GET {{host}}/report/officeId/test5?startDate="2022-01-01"
Content-Type: application/json
#Authorization: Bearer {{token}}





