### Add a vacation
POST {{host}}/vacation
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userId": "{{userId}}",
  "vacationStart" : "2022-03-25",
  "vacationEnd" : "2022-03-27"
}

### Get all vacations
GET {{host}}/vacation/all
Content-Type: application/json
Authorization: Bearer {{token}}

### Get vacation by id
GET {{host}}/vacation/{{vacationId}}
Content-Type: application/json
Authorization: Bearer {{token}}

### Edit vacation
PUT {{host}}/vacation/{{vacationId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userId": "{{userId}}",
  "vacationStart" : "2022-03-28",
  "vacationEnd" : "2022-03-29"
}
### Delete vacation
DELETE {{host}}/vacation/{{vacationId}}
Content-Type: application/json
Authorization: Bearer {{token}}
