package com.exadel.telegrambot.botapi;

public enum BotState {
    START,
    CLIENT_ASK_TODO,
    CLIENT_SHOW_BOOKINGS,
    CLIENT_BOOKING,
    CLIENT_ASK_CITY,
    CLIENT_ASK_OFFICE,
    CLIENT_ASK_BOOKING_TYPE,
    CLIENT_ASK_BOOKING_DATE,
    CLIENT_ASK_BOOKING_FIRST_DAY,
    CLIENT_ASK_BOOKING_LAST_DAY,
    CLIENT_ASK_BOOKING_RECURRING,
    CLIENT_ASK_PARKING,
    CLIENT_ASK_PARKING_CONTINUE,
    CLIENT_ASK_WORKPLACE_PARAMS
}
